services:
  app:
    build: .
    container_name: planta_a_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: planta_a_db
    environment:
      MYSQL_DATABASE: planta_a
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: